name: solvro_translator_with_drift_cache_flutter
description: Solvro Translator client with drift cache
resolution: workspace
repository: https://github.com/solvro/lib-mobile-translator
version: "0.9.1"

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  solvro_translator_core: ^0.8.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  solvro_config: ^1.3.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  drift_dev: ^2.30.0
