name: solvro_translator_generator
description: Generator for Solvro Translator for Dart/Flutter applications.
version: 0.8.0
resolution: workspace
repository: https://github.com/Solvro/lib-mobile-translator

environment:
  sdk: ^3.8.0

dependencies:
  analyzer: ^8.0.0
  build: ^4.0.3
  source_gen: ^4.1.0
  path: ^1.9.1
  json_annotation: ^4.9.0
  meta: ^1.16.0
  solvro_translator_core: ^0.8.0

dev_dependencies:
  solvro_config: ^1.3.0
  test: ^1.24.0
